// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: milesight.proto

package protobuffer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Milesight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceUID            string  `protobuf:"bytes,1,opt,name=DeviceUID,proto3" json:"DeviceUID,omitempty"`
	Time                 string  `protobuf:"bytes,2,opt,name=Time,proto3" json:"Time,omitempty"`
	AccumulatedCurrent   float64 `protobuf:"fixed64,3,opt,name=AccumulatedCurrent,proto3" json:"AccumulatedCurrent,omitempty"`
	InstantaneousCurrent float64 `protobuf:"fixed64,4,opt,name=InstantaneousCurrent,proto3" json:"InstantaneousCurrent,omitempty"`
	MaximumCurrent       float64 `protobuf:"fixed64,5,opt,name=MaximumCurrent,proto3" json:"MaximumCurrent,omitempty"`
	MinimumCurrent       float64 `protobuf:"fixed64,6,opt,name=MinimumCurrent,proto3" json:"MinimumCurrent,omitempty"`
}

func (x *Milesight) Reset() {
	*x = Milesight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_milesight_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Milesight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Milesight) ProtoMessage() {}

func (x *Milesight) ProtoReflect() protoreflect.Message {
	mi := &file_milesight_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Milesight.ProtoReflect.Descriptor instead.
func (*Milesight) Descriptor() ([]byte, []int) {
	return file_milesight_proto_rawDescGZIP(), []int{0}
}

func (x *Milesight) GetDeviceUID() string {
	if x != nil {
		return x.DeviceUID
	}
	return ""
}

func (x *Milesight) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Milesight) GetAccumulatedCurrent() float64 {
	if x != nil {
		return x.AccumulatedCurrent
	}
	return 0
}

func (x *Milesight) GetInstantaneousCurrent() float64 {
	if x != nil {
		return x.InstantaneousCurrent
	}
	return 0
}

func (x *Milesight) GetMaximumCurrent() float64 {
	if x != nil {
		return x.MaximumCurrent
	}
	return 0
}

func (x *Milesight) GetMinimumCurrent() float64 {
	if x != nil {
		return x.MinimumCurrent
	}
	return 0
}

var File_milesight_proto protoreflect.FileDescriptor

var file_milesight_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x22, 0xf1, 0x01, 0x0a, 0x09, 0x4d, 0x69,
	0x6c, 0x65, 0x73, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x55, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x41, 0x63, 0x63,
	0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x12, 0x41, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x64, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x14, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x74, 0x61, 0x6e, 0x65, 0x6f, 0x75, 0x73, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x14, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74,
	0x61, 0x6e, 0x65, 0x6f, 0x75, 0x73, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a,
	0x0e, 0x4d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x4d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x4d,
	0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x0f, 0x5a,
	0x0d, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_milesight_proto_rawDescOnce sync.Once
	file_milesight_proto_rawDescData = file_milesight_proto_rawDesc
)

func file_milesight_proto_rawDescGZIP() []byte {
	file_milesight_proto_rawDescOnce.Do(func() {
		file_milesight_proto_rawDescData = protoimpl.X.CompressGZIP(file_milesight_proto_rawDescData)
	})
	return file_milesight_proto_rawDescData
}

var file_milesight_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_milesight_proto_goTypes = []any{
	(*Milesight)(nil), // 0: energy.Milesight
}
var file_milesight_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_milesight_proto_init() }
func file_milesight_proto_init() {
	if File_milesight_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_milesight_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Milesight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_milesight_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_milesight_proto_goTypes,
		DependencyIndexes: file_milesight_proto_depIdxs,
		MessageInfos:      file_milesight_proto_msgTypes,
	}.Build()
	File_milesight_proto = out.File
	file_milesight_proto_rawDesc = nil
	file_milesight_proto_goTypes = nil
	file_milesight_proto_depIdxs = nil
}
